### ISSUE TITLE
Your name offends me

### ISSUE THREAD

**Issue by TimTheToolManGuy** [Christian-Schiffer/servicelayer.chat#21]
I think using religious names out of context is offensive and i want it changed.

**Comment by Christian-Schiffer** [comment]
Thank you for teaching me the true meaning of xmas, as if I did not know it already. You and those fans of yours upvoting your xmas greeting are yet another bunch of fine examples of why my bug report was necessary. As to my name, it does not offend me, see my grand dad had the same name, he got the choice between Sachsenhausen and the Eastern Front after he kicked some Gestapo ass for harassing a 12 year old Jewish girl. He joined the 6th army and consequently was taken captive and sent to a Gulag in Siberia. In the early 50th he managed to flee from there and went back on his feet back to my Grandma in Bonn, Germany. One year later he died probably from an insulin shock as he tried to eat a tiny piece of his birthday cake. See both He and I are German. So while I indeed, like you, hate the meaning of my name, I am very proud of it due to what my grand dad did. Blessed be his memory.

**Comment by loxs** [comment]
@Christian-Schiffer yup, your grand dad was not a snowflake.

**Comment by Christian-Schiffer** [comment]
> @Christian-Schiffer yup, your grand dad was not a snowflake.

Your right, he most certainly was not.

**Comment by LeonardDrs** [comment]
It's kinda wrong to harass someone for their belief. It's late 2019, y'all suppose to know that.

**Comment by RvstFyth** [comment]
@Christian-Schiffer 
Lots of people enjoyed the little christmas hat. It's also the reason you are receiving this backlash. It's those little things that make us smile. By calling it a offense, you are making it a offense yourself.
Are you gonna avoid walking on the streets during december also? What about tv or social media, you are all gonna avoid it? So why making a big deal out something so small?

**And comparing xmas with swastika's... c'mon dude...**

Also, vscode is opensource. You could have removed the hat yourself and make a build...

**Comment by Trim21** [comment]
Could we Pastafarians have some Spaghettoni in vscode on Pastover, either?

**Comment by RvstFyth** [comment]
@Trim21 i guess not, im pretty sure he will start ranting about how you try to form swastika's with it.

Always someone complaining with their PC bullcrap... And for what? To brag how he made microsoft remove something from their application?

**Comment by Christian-Schiffer** [comment]
> **And comparing xmas with swastika's... c'mon dude...**
Well, feel free to read some of the comments, pull requests and issues opened here since then, they prove my point. I might also add a link to a screenshot of my inbox later on, there you'll see the real xmas spirit coming force behind keyboard warriors hiding behind anonymity and guerrilla mail, making death threats and threatening Genocide and what not. So yes, the comparison unfortunately is very valid, even today.

**Comment by Christian-Schiffer** [comment]
> Also, vscode is opensource. You could have removed the hat yourself and make a build...
Indeed I could, but that is not the point, if the hat is so important to you, why not make a git with an extension for it? That way you can enjoy that horrible thing and at the same time avoid forcing that genocidal symbol down everyone's throat. Tell me, do you like JW's coming to your door trying to force their religion down your throat? Me neither, yet those are just some door, you can easily slam it in their face if you like and they'll leave. The Santa hat on the other hand could not even be removed, without great effort, like compiling my own version.

**Comment by RvstFyth** [comment]
You are just trying to score internet points here buddy.. to be clear i wasn't trolling with my reaction.
And no, i dont have jews at my door but for that i've got Jehova visits like each month. Sometimes ill talk to them, other times i just close the door. No big deal ¯\_(ツ)_/¯
