### ISSUE TITLE
OP name is offensive for me

### ISSUE THREAD

**Issue by GameJamer** [Christian-Schiffer/servicelayer.chat#27]
🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅I mean... how can he be Christian by name but fight santa hats!🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅

**Comment by Christian-Schiffer** [comment]
I can understand why you would question that. While my names meaning indeed offends me like many others who have blessed me with such "nice" xmas greetings the last 24 hours, the name itself does not offend me at all, see I got it after my grandad had the same name, he got the choice between Sachsenhausen and the Eastern Front after he kicked some Gestapo ass for harassing a 12 year old Jewish girl. He joined the 6th army and consequently was taken captive and sent to a Gulag in Siberia. In the early 50th he managed to flee from there and went back on his feet back to my Grandma in Bonn, Germany. One year later he died probably from an insulin shock as he tried to eat a tiny piece of his birthday cake. See both He and I are German. So while I indeed, like you, hate the meaning of my name, I am very proud of it due to what my grand dad did. Blessed be his memory. I wish he had chosen Sachsenhausen though, cause since he was a German, he might would have survived that so I could have had the chance to meet him. I would have liked that very much.

**Comment by x1024** [comment]
Wait, uhhhh... did you just say that your grandfather was a Nazi?

**Comment by Christian-Schiffer** [comment]
> Wait, uhhhh... did you just say that your grandfather was a Nazi?

Is that what you got out of the story?

**Comment by x1024** [comment]
Well, apparently he fought for the Germans in WW2, soooooo....

**Comment by GameJamer** [comment]
Ok boomer.🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅
I still wish you a Merry CHRISTMASS 🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅🎅

**Comment by Christian-Schiffer** [comment]
> Well, apparently he fought for the Germans in WW2, soooooo....

Yes he did, he chose to be sent to the eastern front over being sent to Sachsenhausen. Those were the choices he was presented with after beating up quite a few gestapo's defending a Jewish girl they horraced. Oh, I forgot, there was a third choice too, he could have chosen to be put up against the wall and shot right there and then. Apparently you seem to belive that all Germans were nazis, that was not the case, yet many where, far to many.

**Comment by x1024** [comment]
Holy shit, the grandchild of the Nazi is *still* trying to destroy civilization, all these years later.

Some things never change, I gues...

**Comment by Christian-Schiffer** [comment]
> Ok boomer.
> I still wish you a Merry (Redacted by OP)

I see, you are yet another fine example of why it was necessary to make that bug report, you may not understand it yourselves, but you prove my case.

**Comment by x1024** [comment]
I fully believe that most of the germans that DIDN'T join the Nazi army weren't nazis. But you know, once you put on that stylish uniform with the skulls on it... yeah...

**Comment by Christian-Schiffer** [comment]
> I fully believe that most of the germans that DIDN'T join the Nazi army weren't nazis. But you know, once you put on that stylish uniform with the skulls on it... yeah...

You should read up on your history. May I ask you age?

**Comment by x1024** [comment]
Old enough to know people like you must be fought every step of the way.

**Comment by Christian-Schiffer** [comment]
> I fully believe that most of the germans that DIDN'T join the Nazi army weren't nazis. But you know, once you put on that stylish uniform with the skulls on it... yeah...

You think he went with them willingly, is that really what you got out of his story?

**Comment by x1024** [comment]
You put on the nazi uniform, you're a nazi.

**Comment by Christian-Schiffer** [comment]
> Old enough to know people like you must be fought every step of the way.

I see, well I am old enough to know, that guys like you, would have made excellent Gestapists, eager to serve.

**Comment by x1024** [comment]
Go be proud of your nazi grandfather somewhere else.

**Comment by Christian-Schiffer** [comment]
> You put on the nazi uniform, you're a nazi.

The nazis too where masters as turning things on their heads and oversimplifying issues.

**Comment by x1024** [comment]
Well, when you're *literally wearing a nazi uniform* things tend to be black and white.

**Comment by Christian-Schiffer** [comment]
> Well, when you're _literally wearing a nazi uniform_ things tend to be black and white.

As I said, black and white thinking, turning things on their heads are skills both you and the nazis you claim to hate mastered very well.

**Comment by x1024** [comment]
Yeah, you would know, wouldn't you.

**Comment by Christian-Schiffer** [comment]
> Yeah, you would know, wouldn't you.

Yes I do. I know exactly what kind of people they were and are, thus I know, more likely than not, you would have joined them without a second thought.

**Comment by x1024** [comment]
Well, whatever, let's stop talking about your nazi grandpa. It's clear he was just too much of a coward to be a man and not participate in the genocide of a bunch of non-white and not-white-enough ethnicities, and instead he just chose to go with the flow and kill some innocent people. I mean, it happens to the best of us, who can blame the poor nazi, really.

**Comment by Christian-Schiffer** [comment]
Thank you for the conversation, you most certainly proved all my points.

**Comment by Wilkolicious** [comment]
> I can understand why you would question that. While my names meaning indeed offends me like many others who have blessed me with such "nice" xmas greetings the last 24 hours, the name itself does not offend me at all, see I got it after my grandad who had the same name, he got the choice between Sachsenhausen and the Eastern Front after he kicked some Gestapo ass for harassing a 12 year old Jewish girl. He joined the 6th army and consequently was taken captive at Stalingrad and sent to a Gulag in Siberia. In the early 50th he managed to flee from there and went back on his feet back to my Grandma in Bonn, Germany. One year later he died probably from an insulin shock as he tried to eat a tiny piece of his birthday cake. See both He and I are German. So while I indeed, like many others here, hate the meaning of my name, I am very proud of it due to what my grand dad did. Blessed be his memory. I wish he had chosen Sachsenhausen though, cause since he was a German, he might would have survived that so I could have had the chance to meet him. I would have liked that very much.

I'll bite in case you're not trolling.

So like how the name 'Christian' has changed its meaning to you through the actions your honourable Grandfather took, the nature of 'Christmas' has generally changed socially into an annual event with the intention of spreading fun and gifts.  Its intention is not to damn your ancestors or celebrate their plight.

If you're truly offended by this action taken by MS (as much as I don't want to be a reductionist to your feelings), then I think you need to take a deep breath and review your perspective on this event.  

Putting a santa hat on an icon is amusing to many, and certainly brightened their day up a little.  Instead of going with the flow/moving on with your life, you decided to use religion (Christmas is secular and entertained by the vast majority of atheist who don't feel offended by its distant Christian roots), and your Grandfather to arrogantly push across your personal feelings onto others.  

Should I consider that your Grandfather and/or your religion to be one that removes harmless fun from society?  I don't think that would be the case.  Do you?

**Comment by x1024** [comment]
Don't blame him, he's just continuing his family's legacy.

**Comment by juicegointheoven** [comment]
### I tried to warn you.

**Comment by x1024** [comment]
Thank you, you totally-not-fake-account that was **totally** not just made by @Christian-Schiffer just so that he can pretend he's being targeted.

**Comment by ToaMatatoa** [comment]
> Thank you for the conversation, you most certainly proved all my points.

Now many people know that Microsoft is weak and that Christmas is very important to you. Therefore, we will congratulate you more often. So that you do not spoil the holiday to others. Clown.

**Comment by juicegointheoven** [comment]
> Thank you, you totally-not-fake-account that was **totally** not just made by @Christian-Schiffer just so that he can pretend he's being targeted.
> 
> It is, of course, a coincidence that he stopped writing and literally 4 minutes later your account was created and started writing.

That would be rather sneaky now wouldn't it.

**Comment by x1024** [comment]
Give it up, @Christian-Schiffer, this is getting sad now.

**Comment by juicegointheoven** [comment]
Der Feuhrer takes offense to these accusations of jewery.

**Comment by x1024** [comment]
I reported you to Github support, I explained that this was your alt account, and I don't plan to engage with you any further.

**Comment by juicegointheoven** [comment]
Plz engage @x1024, I have nothing better to do other than open useless issues and screech about muh 6 gorrilion

**Comment by x1024** [comment]
Christian, you're going against your own interests by doing this.

**Comment by Christian-Schiffer** [comment]
> > I can understand why you would question that. While my names meaning indeed offends me like many others who have blessed me with such "nice" xmas greetings the last 24 hours, the name itself does not offend me at all, see I got it after my grandad who had the same name, he got the choice between Sachsenhausen and the Eastern Front after he kicked some Gestapo ass for harassing a 12 year old Jewish girl. He joined the 6th army and consequently was taken captive at Stalingrad and sent to a Gulag in Siberia. In the early 50th he managed to flee from there and went back on his feet back to my Grandma in Bonn, Germany. One year later he died probably from an insulin shock as he tried to eat a tiny piece of his birthday cake. See both He and I are German. So while I indeed, like many others here, hate the meaning of my name, I am very proud of it due to what my grand dad did. Blessed be his memory. I wish he had chosen Sachsenhausen though, cause since he was a German, he might would have survived that so I could have had the chance to meet him. I would have liked that very much.
> 
> I'll bite in case you're not trolling.
> 
> So like how the name 'Christian' has changed its meaning to you through the actions your honourable Grandfather took, the nature of 'Christmas' has generally changed socially into an annual event with the intention of spreading fun and gifts. Its intention is not to damn your ancestors or celebrate their plight.
> 
> If you're truly offended by this action taken by MS (as much as I don't want to be a reductionist to your feelings), then I think you need to take a deep breath and review your perspective on this event.
> 
> Putting a santa hat on an icon is amusing to many, and certainly brightened their day up a little. Instead of going with the flow/moving on with your life, you decided to use religion (Christmas/Xmas is vastly secular and entertained by the vast majority of atheist who don't feel offended by its distant Christian roots), and your Grandfather to arrogantly push across your personal feelings onto others.
> 
> Should I consider that your Grandfather and/or your religion to be one that removes harmless fun from society? I don't think that would be the case. Do you?

Have a look at the hatefest here and tell me the xmas spirit in fact has changed since then. What you see here, even the comments by your new self proclaimed Führer above, by the way is nothing against what has landed in my inbox from some of those xmas warriors using guerrilla mail accounts to send death threats and what not.

If there was ever any better proof that my bug report was absolutely necessary, you'll have no problem finding plenty of it here in the pull requests and Issues posted here since then. If it was possible to post images here, I would add a screenshot of my inbox, I still may, upload it to a server and add a link.

See I started of reporting this hatefest but then I decided to let it stand and keep the threads open, almost each and every message here, make my case for me.

**Comment by Christian-Schiffer** [comment]
> ### I tried to warn you.

As a German anti-nazi in my fifties, I got your warnings long ago, time and time again, if you think they will stop me from doing what is right, think again. Herr Anonymer Möchtegern Führer.

**Comment by AlexWarp** [comment]
People just don't want to see anyone use religion as an excuse to push their personal ideals somewhere where they don't need to be. 
And there are some trolls, I guess?

You, on the other hand, haven't even address any of Wilkolicious points.

**Comment by markeeftb** [comment]
Viber is next!
![Screenshot_20191219_204317](https://user-images.githubusercontent.com/3172570/71204480-846bf200-22a0-11ea-8ada-aa9a972c0915.jpg)

**Comment by Christian-Schiffer** [comment]
> Viber is next!
> ![Screenshot_20191219_204317](https://user-images.githubusercontent.com/3172570/71204480-846bf200-22a0-11ea-8ada-aa9a972c0915.jpg)

Thanks for making me aware of the issue, I just might take you up on that. ;-)

**Comment by Clemens-E** [comment]
While I think that @Christian-Schiffer completely overreacted because of a Hat, it's unbelievable how @x1024 is now calling him and his Grandfather Nazis. As a fellow German, I can only disagree because in that time you where given the choice between staying silent and following directions, or thrown into concentration camps or worse.

**Comment by x1024** [comment]
WOW, what a coincidence, Christian stopped posting here literally as soon as the obviously fake racist account started posting AND he got back literally the exact minute the obviously fake racist account got banned!

**Comment by varadero** [comment]
I can't understand how anyone can be so easily tricked and manipulated to do specific thing like Microsoft and its employees (@egamma ?) were by this @Christian-Schiffer. I bet that guy is LOL-ing right now how s*itty Microsoft is. 

What if I spent a couple of minutes to find something "offensive"... like the "Source Control" icon - it looks like a thin PENIS with two loosely-coupled testicles which, of course, is offensive to all the men on the planet ! Would you @egamma change that icon for me and all other men, please ?

I would recommend everyone to make similar complaint to Microsoft about ridiculously stupid thing like @Christian-Schiffer and I did.

Everyone now will remember Microsoft as one of these companies which went into such stupid trap.
