### ISSUE TITLE
WTF is happening with this repo?

### ISSUE THREAD

**Issue by Lukkian** [Christian-Schiffer/servicelayer.chat#35]

**Comment by juicegointheoven** [comment]
Christmas is under attack.

**Comment by Ekultek** [comment]
we will defend tf outta christmas until the absolute end

**Comment by GreemDev** [comment]
https://github.com/microsoft/vscode/issues/87268

**Comment by Christian-Schiffer** [comment]
The xmas spirit showed its true face I guess. Threats, genocide, claims that 6 mill. weren't enough and such. See I filed a bug report on VS code insiders, asking them to remove the santa hat providing good reason for them to understand how offensive that in fact is to many from their latest update, which Microsoft, of course did. I referred to the possibly millions of people who had been murdered and tortured because of it, documented it, well aware that that unfortunately isn't a thing of the past, as many posts here provide ample proof for. Not to mention the anonymous guerilla mails currently flooding  my mailbox with death threats and threats of genocide as well as the most perverted imagery I have ever encountered.

**Comment by ChrGriffin** [comment]
What happened is that Schiffer here was so thoroughly emotionally broken by the sight of a Santa hat that he opened an issue with VSCode to remove a Santa hat from their latest release. Rather than moving on with his day like a fucking adult.

**Comment by atlassanjay** [comment]
@Christian-Schiffer you reap what you sow

**Comment by x1024** [comment]
According to this disturbed person, millions of people are being killed because of Christmas *in the present*.

**Comment by Reynergodoy** [comment]
> The xmas spirit showed its true face I guess. Threats, genocide, claims that 6 mill. weren't enough and such. See I filed a bug report on VS code insiders, asking them to remove the santa hat providing good reason for them to understand how offensive that in fact is to many from their latest update, which Microsoft, of course did. I referred to the possibly millions of people who had been murdered and tortured because of it, documented it, well aware that that unfortunately isn't a thing of the past, as many posts here provide ample proof for. Not to mention the anonymous guerilla mails currently flooding my mailbox with death threats and threats of genocide as well as the most perverted imagery I have ever encountered. See also GreemDevs link above for context.

I would like plausible evidences of death threats. Assuming you did not fake it.

**Comment by Reynergodoy** [comment]
Oh yeah, I also have evidences of you threatening people using their IP addresses.

**Comment by AmyrAhmady** [comment]
Your name is pushing a religion and it's offensive to me as a Muslim and many other fellow muslim brother.
I'd be glad if you change your name as soon as possible Mr. Christian; It's hurting my feelings and I can't stay on the internet when I know there's someone called Christian, but I'm a developer and I need to work. It's just making it very hard for me.
It is also a reminder of jesus and how badly he died in pain, so your name is also offensive to christian people

Please, change your name, I have evidence of you having that name and I will attach it to this post

![image](https://user-images.githubusercontent.com/34688664/71210863-2a305880-22c3-11ea-8214-cf7d76c3f8ff.png)
