### ISSUE TITLE
I feel offended by your issue, please stop participating in this community because it offends me

### ISSUE THREAD

**Issue by JacekDziurdzikowski** [Christian-Schiffer/servicelayer.chat#36]
The issue you have with santa hat makes me feel offended because of the pettiness of it and it reminds me how meanness some people can be.

**Comment by Christian-Schiffer** [comment]
> because

You and others here achieve nothing but to prove my case.

**Comment by OfficalLooper** [comment]
Its a Santa hat you snowflake. Thanks for ruining something all because you are a weakest person. If it was something Jewish you wouldn't be complaining now would you? if someone says Merry Christmas or Happy Hanukkah to you, then just say it back. How does it offend anyone? Did they pull out a gun or threaten you? NO!, Grow up snowflake!

**Comment by ChrGriffin** [comment]
> > because
> 
> You and others here achieve nothing but to prove my case.

'Case'? What the fuck 'case' do you think you have? It was a Santa hat. Grow the fuck up.

**Comment by ChrGriffin** [comment]
In all seriousness, though. I'm a liberal. I'm an advocate for social justice. I believe we need more women in tech, I believe in multiculturalism, and I have no problem with 'happy holidays'. I'm what the internet would happily call a 'snowflake'.

And my God, this stupid, petty shit pisses me off, because it paints that entire side of the debate with this brush. People associate people like me, with people like you. You, sir, truly are a gigantic fucking snowflake. Get the fuck over yourself.

**Comment by Rexogamer** [comment]
Why the fuck do you have to ruin the fun because “oh my how offensive a FUCKING RED HAT”? Just go into the CSS locally and remove the hat.
