### ISSUE TITLE
An attempt at a reasonable and balanced explanation of why many disagree with you

### ISSUE THREAD

**Issue by seagull-pat** [Christian-Schiffer/servicelayer.chat#47]
For the absolute vast majority of people in Britain certainly (as I cannot speak for the rest of the world), the Santa hat has zero religious meaning. For most people, religion will never have any particular impact on their lives, and yet most people, of many different faiths and beliefs, still celeberate Christmas. In my country, it is in no way representative of Christianity, nor is it a religious symbol.

**Comment by notviri** [comment]
I'd like to think that in most first world countries it's a commercial holiday, not just Britain.

**Comment by seagull-pat** [comment]
I'd also like to add that trolling and spam-issuing of this person's repos is in my opinion a completely unacceptable way to deal with the situation, and really does not reflect well on anyone who has participated in it

**Comment by Rexogamer** [comment]
Honestly I think the best thing would be a toggle for things like Santa hats. People who want to have some festive fun get their fun, while people who find such things offensive can turn it off and no longe feel offended.

**Comment by dmarkhas** [comment]
@seagull-pat I think Microsoft simply threw @Christian-Schiffer under the bus, in order to divert the community's attention from the absolutely horrible way they treated this from the start. None of us would even be here if it wasn't for a Microsoft employee abusing his access to the VSCode repository to remove a feature at his own discretion.
While I totally disagree with @Christian-Schiffer on the matter of Christmas (being Jewish myself), I absolutely respect his right to his own opinion and support his ability to express his opinion. 
It is his right to express concern over a feature of VSCode, and it is our right, as a community, to disagree with him. It is absolutely not within our rights to personally target and bully him, and I sincerely hope that everyone who has taken part in it will be permanently banned from GitHub.

What Microsoft did is absolutely terrible IMO - they immediately removed the feature and banned all discussion about it, while in reality they could've just ignored that issue (like they ignore thousands of other issues) or address it in a more thought out way.  They essentially made @Christian-Schiffer a scapegoat for their cowardly behavior.

**Comment by Rexogamer** [comment]
Honestly, @dmarkhas is right. An employee pretty much IMMEDIATELY removing the hat (even though it was only one person who was against it) is pretty poor behaviour. This also diverts attention from genuine bugs/feature requests.

**Comment by Christian-Schiffer** [comment]
Microsoft did nothing wrong in this matter, nor did the employee removing the hat, it is standard Microsoft Policy to remove offensive symbols from their software as soon as they are made aware of it.

In that respect I would like to direct your attention to a somewhat similar case with the Visual Studio installer containing a green hat which is offensive to many in China: https://developercommunity.visualstudio.com/content/problem/475341/vs-installer-welcome-image-contains-offensive-elem.html

> VS Installer welcome image contains offensive element for Chinese
> Closed - Fixed fixed in: visual studio 2019 version 16.0 rc.2Fixed In: Visual Studio 2017 version 15.9.10Fixed In: Visual Studio 2019 version 16.0visual studio 2019 version 16.0 rcSetupFixed In: Visual Studio 2019 version 16.0 Preview 4
> avatar image Edi Wang reported Mar 02 at 02:17 PM
> After install VS2019 in the Visual Studio Installer. There is a welcome background image showes a guy wearing a GREEN HAT riding a bike.
> 
> However, GREEN HAT is offensive in Chinese culture. A guy with a green hat means his girlfriend or wife is cheating on him.
> 
> Please just Bing “green hat china”, this is serious. Please consider changing the color of the hat in that image.

**Comment by Christian-Schiffer** [comment]
Now while it of course if not very nice to be subjected to mockery over a cheating wife, I would suggest that being murdered, tortured and persecuted in the worst possible way like millions of Jews have been over the centuries due to your xmas traditions, where people wearing just that hat broke into their homes on xmas and beat, tortured and murdered Jewish families for allegedly "murdering their god" is far worse then being mocked over a cheating wife.

**Comment by Christian-Schiffer** [comment]
Now to make it clear to those developers who lack deductive reasoning skills, I mean my given name should be a dead giveaway, I am not Jewish myself, so if you please would refrain from directing your hate against the Jewish people because of me, that would be good. If you want to hate someone, hate me, I really don't care, since these hainous attacks on me some even containing death threats against my person, obviously does not come from people having any moral compass at all.

I mean, really, sending me German Reich flags with swastika symbols, mails where some of you say that 6 million weren't enough and what not, only proves that the xmas spirit of old I address, were people like them used to murder Jews over it, unfortunately is still alive and well in many if not most of those attacking me here and abusing this forum to use me as a proxy for their hatred against the Jewish people.

Is that really something you people wish to associate ourselves with? If so, keep on going.

**Comment by Rexogamer** [comment]
Most of us are not angry at Jews. Oh hell no. Jews are awesome! But most of us (excluding those 4chan brigaders) are annoyed at **you.** Speaking for groups _you’re not even in?_ If it WAS causing actual Jews offence, they’d speak up. But most people would just ignore it or maybe even smile. I’m sorry if you’re getting death threats and hate mail, but you’re not exactly helping your cause.

**Comment by Christian-Schiffer** [comment]
> Most of us are not angry at Jews. Oh hell no. Jews are awesome! But most of us (excluding those 4chan brigaders) are annoyed at **you.** Speaking for groups _you’re not even in?_ If it WAS causing actual Jews offence, they’d speak up. But most people would just ignore it or maybe even smile. I’m sorry if you’re getting death threats and hate mail, but you’re not exactly helping your cause.

I understand, obviously it is my fault that you guys are sending me death threats, try to hack my servers, mount ddos attacks against it, send me santa's making the Hitler salute call me Jewn***er, one of you even sending me me a beautiful image of his rectum, opened wide and what not. So Yes I am obviously a snowflake given I am not particularly amused about any of that. I mean c'mon, is just a little xmas fun, now isn't it?

As I said, thank you guys for confirming the true spirit of xmas yet again, making my case.

**Comment by Rexogamer** [comment]
Way to ignore the point I was making. You’re not Jewish, and yet you have
to ruin the fun. Again, I do not, in *ANY conceivable way, condone the
actions of a lot of the people here. The actions of some of these people
are horrid. *But speaking for a group that you’re not in and didn’t raise
any issues about this? It seems like the definition of a white knight.

**Comment by Christian-Schiffer** [comment]
> Way to ignore the point I was making. You’re not Jewish, and yet you have to ruin the fun. Again, I do not, in *ANY conceivable way, condone the actions of a lot of the people here. The actions of some of these people are horrid. *But speaking for a group that you’re not in and didn’t raise any issues about this? It seems like the definition of a white knight.
> […](#)
> On Sat, 21 Dec 2019 at 11:01, Christian Schiffer ***@***.***> wrote: Most of us are not angry at Jews. Oh hell no. Jews are awesome! But most of us (excluding those 4chan brigaders) are annoyed at *you.* Speaking for groups *you’re not even in?* If it WAS causing actual Jews offence, they’d speak up. But most people would just ignore it or maybe even smile. I’m sorry if you’re getting death threats and hate mail, but you’re not exactly helping your cause. I understand, obviously it is my fault that you guys are sending me death threats, try to hack my servers, mount ddos attacks against it, send me santa's making the Hitler salute call me Jewn***er, one of you even sending me me a beautiful image of his rectum, opened wide and what not. So Yes I am obviously a snowflake given I am not particularly amused about any of that. I mean c'mon, is just a little xmas fun, now isn't it? As I said, thank you guys for confirming the true spirit of xmas yet again, making my case. — You are receiving this because you commented. >

I would think you guys have a lot of fun right now, hating me.

**Comment by Rexogamer** [comment]
I’m not talking about the “fun” of hating on you! I’m talking about the fun of having a **SANTA HAT ON A COG ICON.**

**Comment by Christian-Schiffer** [comment]
> I’m not talking about the “fun” of hating on you! I’m talking about the fun of having a **RED HAT ON A COG ICON.**

Indeed, that is what this is all about, that symbol being used again and again in murderous and even genocidal attacks against people you do not like.

**Comment by Rexogamer** [comment]
This is basically what I thought should happen:
>>> Looking forward…

If you’ve looked at our settings, you know that you get a lot of choice with VS Code. We decided to follow this pattern and let users configure how the gear looks. We’ve added a new setting to Insiders that lets you choose the icon. If you like the red hat, go for it! Maybe you live in the southern hemisphere or you are heading to the beach during the holidays, there’s an icon for you too.

Open settings (Mac: CMD+, Windows/Linux: CTRL+,) and search for “Holiday Gear Icon Style”, and choose your icon
If you love editing settings.json, set holiday.gearIconStyle
You will still find the “Happy Holidays” command which will bring up the overlay, snow, and message.

And finally, as we did in previous years, we will remove this little treat around the first week of January. In the meantime, download Insiders now and have a happy holiday season from all of us in Redmond and Zurich.

**Comment by Christian-Schiffer** [comment]
> This is basically what I thought should happen:
> 
> > **Looking forward…**
> > If you’ve looked at our settings, you know that you get a lot of choice with VS Code. We decided to follow this pattern and let users configure how the gear looks. We’ve added a new setting to Insiders that lets you choose the icon. If you like the red hat, go for it! Maybe you live in the southern hemisphere or you are heading to the beach during the holidays, there’s an icon for you too.
> > `Open settings (Mac: CMD+, Windows/Linux: CTRL+,) and search for “Holiday Gear Icon Style”, and choose your icon`
> > `If you love editing settings.json, set holiday.gearIconStyle`
> > You will still find the “Happy Holidays” command which will bring up the overlay, snow, and message.
> > And finally, as we did in previous years, we will remove this little treat around the first week of January. In the meantime, download Insiders now and have a happy holiday season from all of us in Redmond and Zurich.
> 
> Yay! People can celebrate the holidays, but if you don’t like it you can turn it off. IMO, the best solution.

Yes, I would think that is the best solution, does that mean you guys are done with your xmas hatefest against me as proxy for your hate of Jews?

**Comment by Rexogamer** [comment]
Calm down. In summary: **yes**. I personally am not against Jews but I believe 4chan was involved, and they’re not exactly supportive of Jews. I don’t wish ill will on you, good luck with this app.

**Comment by Christian-Schiffer** [comment]
Just to let you know, before I filed that issue, I did try to find a way to remove it through configuration, I'll add a portion of my search history for your convenience.

Found 121 search results for 'visual studio'
Dec 18, 2019
microsoft/vscode: Visual Studio Code
github.com
Dec 18, 2019
(21) Visual Studio Code - Home
www.facebook.com
Dec 18, 2019
Download Visual Studio Code Insiders
code.visualstudio.com
Dec 18, 2019
Evolution of Visual Studio Code Insiders
code.visualstudio.com
Dec 18, 2019
Documentation for Visual Studio Code
code.visualstudio.com
Dec 18, 2019
Visual Studio Code November 2019
code.visualstudio.com
Dec 18, 2019
visual studio code - How to downgrade vscode - Stack Overflow
stackoverflow.com
Dec 18, 2019
go back to previous version of visual studio code insiders - Google Search
www.google.com
Dec 18, 2019
"remove" updates from visual studio code insiders - Google Search
www.google.com
Dec 18, 2019
remove updates from visual studio code insiders - Google Search
www.google.com
Dec 18, 2019
remove updates from visual studio insiders - Google Search
www.google.com
Dec 18, 2019
remove updates from visual studio insider - Google Search
www.google.com
Dec 18, 2019
visual studio code santa hat - Google Search
www.google.com
Dec 18, 2019
visual studio code santa hat - Google Search
www.google.com
Dec 18, 2019
Search - Developer Community
developercommunity.visualstudio.com
Dec 18, 2019
remove the santa hat from visual studio code - Google Search
www.google.com
Dec 18, 2019
remove the santa hats from visual studio code - Google Search
www.google.com
Dec 18, 2019
Remove the Santa Hats from visual studio code - Google Search
www.google.com
Dec 18, 2019
how to "remove the santa" from "visual studio code" - Google Search
www.google.com
Dec 18, 2019
how to "remove" the santa from visual studio code - Google Search
www.google.com
Dec 18, 2019
how to remove the santa from visual studio code - Google Search
www.google.com
Dec 18, 2019
Download Visual Studio Code - Mac, Linux, Windows
code.visualstudio.com
Dec 18, 2019
(3) Visual Studio Code on Twitter: "Happy holidays - we shipped @code 1.8.0 with lots of enhancements. Get It: https://t.co/dDMIFTRxMn Release notes: https://t.co/KSoAZcpY1G" / Twitter
twitter.com
Dec 18, 2019
visual studio code how to remove the "happy holidays" - Google Search
www.google.com
Dec 18, 2019
visual studio code how to remove the "santa hat" - Google Search
www.google.com

**Comment by Rexogamer** [comment]
That’s fair. I personally feel that none of this would’ve happened if Microsoft made it optional, and in the future I think they will after this.

**Comment by Christian-Schiffer** [comment]
> Please calm down a bit. I understand you’re angry, but breathe for a minute. In summary: **yes**. I personally am not against Jews but I believe 4chan was involved, and they’re not exactly supportive of Jews. I don’t wish ill will on you, good luck with this app.

I am perfectly calm, I am pleased to hear that you say you do not hate Jews, blaming it all on 4chan though. Yet consider this, why would you associate yourselves with such a hatefest if what you are saying is true? See if what you say were true, would it not be more logical to support me and fight the hate instead of partaking in it? Some here say its not a religious symbol, well, for something that is supposedly not religious, you guys sure exhibit a lot of hate otherwise only exhibited by some of the most extremist religious people. 

I would like you all to reflect on that and I hope you guys in the future will be more considered of others and not repeat such a hatefest as you exposed me and also the Jewish people, people of color and others to because you did not like my complaint about that symbol, a symbol your reaction yet again proves is a symbol of hate.

**Comment by Christian-Schiffer** [comment]
> That’s fair. I personally feel that none of this would’ve happened if Microsoft made it optional, and in the future I think they will after this.

Ahh so now it's Microsoft's fault that you guys instigated a hatefest against me. Right, you know in psychology that is called deflection, you should look it up. Now I am not someone unable to forgive, but if this is an attempt to ask for forgiveness, this is not the way, to ask for forgiveness, you need to admit to your wrong doing, admit it was you fault and not blame your own reaction on others. I assure you, anyone who is man or woman enough to do that, will receive my forgiveness in full.

**Comment by Christian-Schiffer** [comment]
I hope we now all can put this behind us an have happy holidays those of us who have them and put an end to it here. I hope we can all agree on that at least.

Happy Holidays, whatever your holiday may be and those who do not celebrate anything these days, I wish you happy coding. Because coding is what this community is all about, let us therefore all go back to just that, either now, or after our respective holiday.
